name: Validate devcontainer-feature.json files

on:
  pull_request:
  push:
    branches: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/action@v1
        with:
          base-path-to-features: "./src"
          validate-only: "true"
